// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: equipment.proto

package equipment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EquipmentService_CreateEquipment_FullMethodName     = "/truesim.equipment.EquipmentService/CreateEquipment"
	EquipmentService_GetEquipment_FullMethodName        = "/truesim.equipment.EquipmentService/GetEquipment"
	EquipmentService_UpdateEquipment_FullMethodName     = "/truesim.equipment.EquipmentService/UpdateEquipment"
	EquipmentService_DeleteEquipment_FullMethodName     = "/truesim.equipment.EquipmentService/DeleteEquipment"
	EquipmentService_ListEquipment_FullMethodName       = "/truesim.equipment.EquipmentService/ListEquipment"
	EquipmentService_AddSensor_FullMethodName           = "/truesim.equipment.EquipmentService/AddSensor"
	EquipmentService_UpdateSensor_FullMethodName        = "/truesim.equipment.EquipmentService/UpdateSensor"
	EquipmentService_RemoveSensor_FullMethodName        = "/truesim.equipment.EquipmentService/RemoveSensor"
	EquipmentService_AddWeapon_FullMethodName           = "/truesim.equipment.EquipmentService/AddWeapon"
	EquipmentService_UpdateWeapon_FullMethodName        = "/truesim.equipment.EquipmentService/UpdateWeapon"
	EquipmentService_RemoveWeapon_FullMethodName        = "/truesim.equipment.EquipmentService/RemoveWeapon"
	EquipmentService_AddCommunication_FullMethodName    = "/truesim.equipment.EquipmentService/AddCommunication"
	EquipmentService_UpdateCommunication_FullMethodName = "/truesim.equipment.EquipmentService/UpdateCommunication"
	EquipmentService_RemoveCommunication_FullMethodName = "/truesim.equipment.EquipmentService/RemoveCommunication"
	EquipmentService_GetVersionHistory_FullMethodName   = "/truesim.equipment.EquipmentService/GetVersionHistory"
	EquipmentService_CompareVersions_FullMethodName     = "/truesim.equipment.EquipmentService/CompareVersions"
	EquipmentService_RollbackVersion_FullMethodName     = "/truesim.equipment.EquipmentService/RollbackVersion"
	EquipmentService_LockEquipment_FullMethodName       = "/truesim.equipment.EquipmentService/LockEquipment"
	EquipmentService_UnlockEquipment_FullMethodName     = "/truesim.equipment.EquipmentService/UnlockEquipment"
	EquipmentService_WatchEquipment_FullMethodName      = "/truesim.equipment.EquipmentService/WatchEquipment"
	EquipmentService_ImportEquipment_FullMethodName     = "/truesim.equipment.EquipmentService/ImportEquipment"
	EquipmentService_ExportEquipment_FullMethodName     = "/truesim.equipment.EquipmentService/ExportEquipment"
)

// EquipmentServiceClient is the client API for EquipmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EquipmentServiceClient interface {
	// CRUD
	CreateEquipment(ctx context.Context, in *CreateEquipmentRequest, opts ...grpc.CallOption) (*Equipment, error)
	GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...grpc.CallOption) (*Equipment, error)
	UpdateEquipment(ctx context.Context, in *UpdateEquipmentRequest, opts ...grpc.CallOption) (*Equipment, error)
	DeleteEquipment(ctx context.Context, in *DeleteEquipmentRequest, opts ...grpc.CallOption) (*Empty, error)
	ListEquipment(ctx context.Context, in *ListEquipmentRequest, opts ...grpc.CallOption) (*ListEquipmentResponse, error)
	// 子系统管理
	AddSensor(ctx context.Context, in *AddSensorRequest, opts ...grpc.CallOption) (*SensorConfig, error)
	UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*SensorConfig, error)
	RemoveSensor(ctx context.Context, in *RemoveSensorRequest, opts ...grpc.CallOption) (*Empty, error)
	AddWeapon(ctx context.Context, in *AddWeaponRequest, opts ...grpc.CallOption) (*WeaponConfig, error)
	UpdateWeapon(ctx context.Context, in *UpdateWeaponRequest, opts ...grpc.CallOption) (*WeaponConfig, error)
	RemoveWeapon(ctx context.Context, in *RemoveWeaponRequest, opts ...grpc.CallOption) (*Empty, error)
	AddCommunication(ctx context.Context, in *AddCommRequest, opts ...grpc.CallOption) (*CommConfig, error)
	UpdateCommunication(ctx context.Context, in *UpdateCommRequest, opts ...grpc.CallOption) (*CommConfig, error)
	RemoveCommunication(ctx context.Context, in *RemoveCommRequest, opts ...grpc.CallOption) (*Empty, error)
	// 版本管理
	GetVersionHistory(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionHistory, error)
	CompareVersions(ctx context.Context, in *CompareVersionsRequest, opts ...grpc.CallOption) (*VersionDiff, error)
	RollbackVersion(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*Equipment, error)
	// 协同
	LockEquipment(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	UnlockEquipment(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*Empty, error)
	WatchEquipment(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EquipmentUpdate], error)
	// 批量操作
	ImportEquipment(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResult, error)
	ExportEquipment(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResult, error)
}

type equipmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEquipmentServiceClient(cc grpc.ClientConnInterface) EquipmentServiceClient {
	return &equipmentServiceClient{cc}
}

func (c *equipmentServiceClient) CreateEquipment(ctx context.Context, in *CreateEquipmentRequest, opts ...grpc.CallOption) (*Equipment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Equipment)
	err := c.cc.Invoke(ctx, EquipmentService_CreateEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...grpc.CallOption) (*Equipment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Equipment)
	err := c.cc.Invoke(ctx, EquipmentService_GetEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) UpdateEquipment(ctx context.Context, in *UpdateEquipmentRequest, opts ...grpc.CallOption) (*Equipment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Equipment)
	err := c.cc.Invoke(ctx, EquipmentService_UpdateEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) DeleteEquipment(ctx context.Context, in *DeleteEquipmentRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, EquipmentService_DeleteEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ListEquipment(ctx context.Context, in *ListEquipmentRequest, opts ...grpc.CallOption) (*ListEquipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEquipmentResponse)
	err := c.cc.Invoke(ctx, EquipmentService_ListEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) AddSensor(ctx context.Context, in *AddSensorRequest, opts ...grpc.CallOption) (*SensorConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorConfig)
	err := c.cc.Invoke(ctx, EquipmentService_AddSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*SensorConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorConfig)
	err := c.cc.Invoke(ctx, EquipmentService_UpdateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) RemoveSensor(ctx context.Context, in *RemoveSensorRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, EquipmentService_RemoveSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) AddWeapon(ctx context.Context, in *AddWeaponRequest, opts ...grpc.CallOption) (*WeaponConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeaponConfig)
	err := c.cc.Invoke(ctx, EquipmentService_AddWeapon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) UpdateWeapon(ctx context.Context, in *UpdateWeaponRequest, opts ...grpc.CallOption) (*WeaponConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeaponConfig)
	err := c.cc.Invoke(ctx, EquipmentService_UpdateWeapon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) RemoveWeapon(ctx context.Context, in *RemoveWeaponRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, EquipmentService_RemoveWeapon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) AddCommunication(ctx context.Context, in *AddCommRequest, opts ...grpc.CallOption) (*CommConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommConfig)
	err := c.cc.Invoke(ctx, EquipmentService_AddCommunication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) UpdateCommunication(ctx context.Context, in *UpdateCommRequest, opts ...grpc.CallOption) (*CommConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommConfig)
	err := c.cc.Invoke(ctx, EquipmentService_UpdateCommunication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) RemoveCommunication(ctx context.Context, in *RemoveCommRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, EquipmentService_RemoveCommunication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) GetVersionHistory(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*VersionHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionHistory)
	err := c.cc.Invoke(ctx, EquipmentService_GetVersionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) CompareVersions(ctx context.Context, in *CompareVersionsRequest, opts ...grpc.CallOption) (*VersionDiff, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionDiff)
	err := c.cc.Invoke(ctx, EquipmentService_CompareVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) RollbackVersion(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*Equipment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Equipment)
	err := c.cc.Invoke(ctx, EquipmentService_RollbackVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) LockEquipment(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, EquipmentService_LockEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) UnlockEquipment(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, EquipmentService_UnlockEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) WatchEquipment(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EquipmentUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EquipmentService_ServiceDesc.Streams[0], EquipmentService_WatchEquipment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, EquipmentUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EquipmentService_WatchEquipmentClient = grpc.ServerStreamingClient[EquipmentUpdate]

func (c *equipmentServiceClient) ImportEquipment(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportResult)
	err := c.cc.Invoke(ctx, EquipmentService_ImportEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ExportEquipment(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResult)
	err := c.cc.Invoke(ctx, EquipmentService_ExportEquipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EquipmentServiceServer is the server API for EquipmentService service.
// All implementations must embed UnimplementedEquipmentServiceServer
// for forward compatibility.
type EquipmentServiceServer interface {
	// CRUD
	CreateEquipment(context.Context, *CreateEquipmentRequest) (*Equipment, error)
	GetEquipment(context.Context, *GetEquipmentRequest) (*Equipment, error)
	UpdateEquipment(context.Context, *UpdateEquipmentRequest) (*Equipment, error)
	DeleteEquipment(context.Context, *DeleteEquipmentRequest) (*Empty, error)
	ListEquipment(context.Context, *ListEquipmentRequest) (*ListEquipmentResponse, error)
	// 子系统管理
	AddSensor(context.Context, *AddSensorRequest) (*SensorConfig, error)
	UpdateSensor(context.Context, *UpdateSensorRequest) (*SensorConfig, error)
	RemoveSensor(context.Context, *RemoveSensorRequest) (*Empty, error)
	AddWeapon(context.Context, *AddWeaponRequest) (*WeaponConfig, error)
	UpdateWeapon(context.Context, *UpdateWeaponRequest) (*WeaponConfig, error)
	RemoveWeapon(context.Context, *RemoveWeaponRequest) (*Empty, error)
	AddCommunication(context.Context, *AddCommRequest) (*CommConfig, error)
	UpdateCommunication(context.Context, *UpdateCommRequest) (*CommConfig, error)
	RemoveCommunication(context.Context, *RemoveCommRequest) (*Empty, error)
	// 版本管理
	GetVersionHistory(context.Context, *GetVersionRequest) (*VersionHistory, error)
	CompareVersions(context.Context, *CompareVersionsRequest) (*VersionDiff, error)
	RollbackVersion(context.Context, *RollbackRequest) (*Equipment, error)
	// 协同
	LockEquipment(context.Context, *LockRequest) (*LockResponse, error)
	UnlockEquipment(context.Context, *UnlockRequest) (*Empty, error)
	WatchEquipment(*WatchRequest, grpc.ServerStreamingServer[EquipmentUpdate]) error
	// 批量操作
	ImportEquipment(context.Context, *ImportRequest) (*ImportResult, error)
	ExportEquipment(context.Context, *ExportRequest) (*ExportResult, error)
	mustEmbedUnimplementedEquipmentServiceServer()
}

// UnimplementedEquipmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEquipmentServiceServer struct{}

func (UnimplementedEquipmentServiceServer) CreateEquipment(context.Context, *CreateEquipmentRequest) (*Equipment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) GetEquipment(context.Context, *GetEquipmentRequest) (*Equipment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) UpdateEquipment(context.Context, *UpdateEquipmentRequest) (*Equipment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) DeleteEquipment(context.Context, *DeleteEquipmentRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) ListEquipment(context.Context, *ListEquipmentRequest) (*ListEquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) AddSensor(context.Context, *AddSensorRequest) (*SensorConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSensor not implemented")
}
func (UnimplementedEquipmentServiceServer) UpdateSensor(context.Context, *UpdateSensorRequest) (*SensorConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSensor not implemented")
}
func (UnimplementedEquipmentServiceServer) RemoveSensor(context.Context, *RemoveSensorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSensor not implemented")
}
func (UnimplementedEquipmentServiceServer) AddWeapon(context.Context, *AddWeaponRequest) (*WeaponConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWeapon not implemented")
}
func (UnimplementedEquipmentServiceServer) UpdateWeapon(context.Context, *UpdateWeaponRequest) (*WeaponConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWeapon not implemented")
}
func (UnimplementedEquipmentServiceServer) RemoveWeapon(context.Context, *RemoveWeaponRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWeapon not implemented")
}
func (UnimplementedEquipmentServiceServer) AddCommunication(context.Context, *AddCommRequest) (*CommConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommunication not implemented")
}
func (UnimplementedEquipmentServiceServer) UpdateCommunication(context.Context, *UpdateCommRequest) (*CommConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCommunication not implemented")
}
func (UnimplementedEquipmentServiceServer) RemoveCommunication(context.Context, *RemoveCommRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCommunication not implemented")
}
func (UnimplementedEquipmentServiceServer) GetVersionHistory(context.Context, *GetVersionRequest) (*VersionHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersionHistory not implemented")
}
func (UnimplementedEquipmentServiceServer) CompareVersions(context.Context, *CompareVersionsRequest) (*VersionDiff, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompareVersions not implemented")
}
func (UnimplementedEquipmentServiceServer) RollbackVersion(context.Context, *RollbackRequest) (*Equipment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackVersion not implemented")
}
func (UnimplementedEquipmentServiceServer) LockEquipment(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) UnlockEquipment(context.Context, *UnlockRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) WatchEquipment(*WatchRequest, grpc.ServerStreamingServer[EquipmentUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method WatchEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) ImportEquipment(context.Context, *ImportRequest) (*ImportResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) ExportEquipment(context.Context, *ExportRequest) (*ExportResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportEquipment not implemented")
}
func (UnimplementedEquipmentServiceServer) mustEmbedUnimplementedEquipmentServiceServer() {}
func (UnimplementedEquipmentServiceServer) testEmbeddedByValue()                          {}

// UnsafeEquipmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EquipmentServiceServer will
// result in compilation errors.
type UnsafeEquipmentServiceServer interface {
	mustEmbedUnimplementedEquipmentServiceServer()
}

func RegisterEquipmentServiceServer(s grpc.ServiceRegistrar, srv EquipmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedEquipmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EquipmentService_ServiceDesc, srv)
}

func _EquipmentService_CreateEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).CreateEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_CreateEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).CreateEquipment(ctx, req.(*CreateEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_GetEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).GetEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_GetEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).GetEquipment(ctx, req.(*GetEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_UpdateEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UpdateEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_UpdateEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UpdateEquipment(ctx, req.(*UpdateEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_DeleteEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).DeleteEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_DeleteEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).DeleteEquipment(ctx, req.(*DeleteEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ListEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ListEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_ListEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ListEquipment(ctx, req.(*ListEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_AddSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).AddSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_AddSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).AddSensor(ctx, req.(*AddSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_UpdateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UpdateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_UpdateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UpdateSensor(ctx, req.(*UpdateSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_RemoveSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).RemoveSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_RemoveSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).RemoveSensor(ctx, req.(*RemoveSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_AddWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).AddWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_AddWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).AddWeapon(ctx, req.(*AddWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_UpdateWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UpdateWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_UpdateWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UpdateWeapon(ctx, req.(*UpdateWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_RemoveWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).RemoveWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_RemoveWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).RemoveWeapon(ctx, req.(*RemoveWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_AddCommunication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).AddCommunication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_AddCommunication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).AddCommunication(ctx, req.(*AddCommRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_UpdateCommunication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UpdateCommunication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_UpdateCommunication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UpdateCommunication(ctx, req.(*UpdateCommRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_RemoveCommunication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCommRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).RemoveCommunication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_RemoveCommunication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).RemoveCommunication(ctx, req.(*RemoveCommRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_GetVersionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).GetVersionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_GetVersionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).GetVersionHistory(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_CompareVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).CompareVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_CompareVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).CompareVersions(ctx, req.(*CompareVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_RollbackVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).RollbackVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_RollbackVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).RollbackVersion(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_LockEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).LockEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_LockEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).LockEquipment(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_UnlockEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UnlockEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_UnlockEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UnlockEquipment(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_WatchEquipment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EquipmentServiceServer).WatchEquipment(m, &grpc.GenericServerStream[WatchRequest, EquipmentUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EquipmentService_WatchEquipmentServer = grpc.ServerStreamingServer[EquipmentUpdate]

func _EquipmentService_ImportEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ImportEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_ImportEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ImportEquipment(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ExportEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ExportEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EquipmentService_ExportEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ExportEquipment(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EquipmentService_ServiceDesc is the grpc.ServiceDesc for EquipmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EquipmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "truesim.equipment.EquipmentService",
	HandlerType: (*EquipmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEquipment",
			Handler:    _EquipmentService_CreateEquipment_Handler,
		},
		{
			MethodName: "GetEquipment",
			Handler:    _EquipmentService_GetEquipment_Handler,
		},
		{
			MethodName: "UpdateEquipment",
			Handler:    _EquipmentService_UpdateEquipment_Handler,
		},
		{
			MethodName: "DeleteEquipment",
			Handler:    _EquipmentService_DeleteEquipment_Handler,
		},
		{
			MethodName: "ListEquipment",
			Handler:    _EquipmentService_ListEquipment_Handler,
		},
		{
			MethodName: "AddSensor",
			Handler:    _EquipmentService_AddSensor_Handler,
		},
		{
			MethodName: "UpdateSensor",
			Handler:    _EquipmentService_UpdateSensor_Handler,
		},
		{
			MethodName: "RemoveSensor",
			Handler:    _EquipmentService_RemoveSensor_Handler,
		},
		{
			MethodName: "AddWeapon",
			Handler:    _EquipmentService_AddWeapon_Handler,
		},
		{
			MethodName: "UpdateWeapon",
			Handler:    _EquipmentService_UpdateWeapon_Handler,
		},
		{
			MethodName: "RemoveWeapon",
			Handler:    _EquipmentService_RemoveWeapon_Handler,
		},
		{
			MethodName: "AddCommunication",
			Handler:    _EquipmentService_AddCommunication_Handler,
		},
		{
			MethodName: "UpdateCommunication",
			Handler:    _EquipmentService_UpdateCommunication_Handler,
		},
		{
			MethodName: "RemoveCommunication",
			Handler:    _EquipmentService_RemoveCommunication_Handler,
		},
		{
			MethodName: "GetVersionHistory",
			Handler:    _EquipmentService_GetVersionHistory_Handler,
		},
		{
			MethodName: "CompareVersions",
			Handler:    _EquipmentService_CompareVersions_Handler,
		},
		{
			MethodName: "RollbackVersion",
			Handler:    _EquipmentService_RollbackVersion_Handler,
		},
		{
			MethodName: "LockEquipment",
			Handler:    _EquipmentService_LockEquipment_Handler,
		},
		{
			MethodName: "UnlockEquipment",
			Handler:    _EquipmentService_UnlockEquipment_Handler,
		},
		{
			MethodName: "ImportEquipment",
			Handler:    _EquipmentService_ImportEquipment_Handler,
		},
		{
			MethodName: "ExportEquipment",
			Handler:    _EquipmentService_ExportEquipment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEquipment",
			Handler:       _EquipmentService_WatchEquipment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "equipment.proto",
}
