// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.9.1
// source: afsim_control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control commands sent from Go gateway to the WSF plugin
// Wire format: [4 bytes little-endian length][serialized ControlCommand]
type ControlCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // for request/response correlation
	// Types that are valid to be assigned to Command:
	//
	//	*ControlCommand_Pause
	//	*ControlCommand_Resume
	//	*ControlCommand_Step
	//	*ControlCommand_SetClockRate
	//	*ControlCommand_Terminate
	Command       isControlCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_afsim_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_afsim_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_afsim_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlCommand) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *ControlCommand) GetCommand() isControlCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlCommand) GetPause() *PauseCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *ControlCommand) GetResume() *ResumeCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *ControlCommand) GetStep() *StepCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Step); ok {
			return x.Step
		}
	}
	return nil
}

func (x *ControlCommand) GetSetClockRate() *SetClockRate {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_SetClockRate); ok {
			return x.SetClockRate
		}
	}
	return nil
}

func (x *ControlCommand) GetTerminate() *TerminateCommand {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Terminate); ok {
			return x.Terminate
		}
	}
	return nil
}

type isControlCommand_Command interface {
	isControlCommand_Command()
}

type ControlCommand_Pause struct {
	Pause *PauseCommand `protobuf:"bytes,2,opt,name=pause,proto3,oneof"`
}

type ControlCommand_Resume struct {
	Resume *ResumeCommand `protobuf:"bytes,3,opt,name=resume,proto3,oneof"`
}

type ControlCommand_Step struct {
	Step *StepCommand `protobuf:"bytes,4,opt,name=step,proto3,oneof"`
}

type ControlCommand_SetClockRate struct {
	SetClockRate *SetClockRate `protobuf:"bytes,5,opt,name=set_clock_rate,json=setClockRate,proto3,oneof"`
}

type ControlCommand_Terminate struct {
	Terminate *TerminateCommand `protobuf:"bytes,6,opt,name=terminate,proto3,oneof"`
}

func (*ControlCommand_Pause) isControlCommand_Command() {}

func (*ControlCommand_Resume) isControlCommand_Command() {}

func (*ControlCommand_Step) isControlCommand_Command() {}

func (*ControlCommand_SetClockRate) isControlCommand_Command() {}

func (*ControlCommand_Terminate) isControlCommand_Command() {}

type PauseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseCommand) Reset() {
	*x = PauseCommand{}
	mi := &file_afsim_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseCommand) ProtoMessage() {}

func (x *PauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_afsim_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseCommand.ProtoReflect.Descriptor instead.
func (*PauseCommand) Descriptor() ([]byte, []int) {
	return file_afsim_control_proto_rawDescGZIP(), []int{1}
}

type ResumeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeCommand) Reset() {
	*x = ResumeCommand{}
	mi := &file_afsim_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeCommand) ProtoMessage() {}

func (x *ResumeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_afsim_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeCommand.ProtoReflect.Descriptor instead.
func (*ResumeCommand) Descriptor() ([]byte, []int) {
	return file_afsim_control_proto_rawDescGZIP(), []int{2}
}

type StepCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepTime      float64                `protobuf:"fixed64,1,opt,name=step_time,json=stepTime,proto3" json:"step_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepCommand) Reset() {
	*x = StepCommand{}
	mi := &file_afsim_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepCommand) ProtoMessage() {}

func (x *StepCommand) ProtoReflect() protoreflect.Message {
	mi := &file_afsim_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepCommand.ProtoReflect.Descriptor instead.
func (*StepCommand) Descriptor() ([]byte, []int) {
	return file_afsim_control_proto_rawDescGZIP(), []int{3}
}

func (x *StepCommand) GetStepTime() float64 {
	if x != nil {
		return x.StepTime
	}
	return 0
}

type SetClockRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float64                `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClockRate) Reset() {
	*x = SetClockRate{}
	mi := &file_afsim_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClockRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClockRate) ProtoMessage() {}

func (x *SetClockRate) ProtoReflect() protoreflect.Message {
	mi := &file_afsim_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClockRate.ProtoReflect.Descriptor instead.
func (*SetClockRate) Descriptor() ([]byte, []int) {
	return file_afsim_control_proto_rawDescGZIP(), []int{4}
}

func (x *SetClockRate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type TerminateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateCommand) Reset() {
	*x = TerminateCommand{}
	mi := &file_afsim_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateCommand) ProtoMessage() {}

func (x *TerminateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_afsim_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateCommand.ProtoReflect.Descriptor instead.
func (*TerminateCommand) Descriptor() ([]byte, []int) {
	return file_afsim_control_proto_rawDescGZIP(), []int{5}
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_afsim_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_afsim_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_afsim_control_proto_rawDescGZIP(), []int{6}
}

func (x *ControlResponse) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_afsim_control_proto protoreflect.FileDescriptor

const file_afsim_control_proto_rawDesc = "" +
	"\n" +
	"\x13afsim_control.proto\x12\rafsim.control\"\xdf\x02\n" +
	"\x0eControlCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\x123\n" +
	"\x05pause\x18\x02 \x01(\v2\x1b.afsim.control.PauseCommandH\x00R\x05pause\x126\n" +
	"\x06resume\x18\x03 \x01(\v2\x1c.afsim.control.ResumeCommandH\x00R\x06resume\x120\n" +
	"\x04step\x18\x04 \x01(\v2\x1a.afsim.control.StepCommandH\x00R\x04step\x12C\n" +
	"\x0eset_clock_rate\x18\x05 \x01(\v2\x1b.afsim.control.SetClockRateH\x00R\fsetClockRate\x12?\n" +
	"\tterminate\x18\x06 \x01(\v2\x1f.afsim.control.TerminateCommandH\x00R\tterminateB\t\n" +
	"\acommand\"\x0e\n" +
	"\fPauseCommand\"\x0f\n" +
	"\rResumeCommand\"*\n" +
	"\vStepCommand\x12\x1b\n" +
	"\tstep_time\x18\x01 \x01(\x01R\bstepTime\"\"\n" +
	"\fSetClockRate\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x01R\x04rate\"\x12\n" +
	"\x10TerminateCommand\"o\n" +
	"\x0fControlResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessageB3H\x03Z/github.com/truesim/afsim-gateway/internal/protob\x06proto3"

var (
	file_afsim_control_proto_rawDescOnce sync.Once
	file_afsim_control_proto_rawDescData []byte
)

func file_afsim_control_proto_rawDescGZIP() []byte {
	file_afsim_control_proto_rawDescOnce.Do(func() {
		file_afsim_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_afsim_control_proto_rawDesc), len(file_afsim_control_proto_rawDesc)))
	})
	return file_afsim_control_proto_rawDescData
}

var file_afsim_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_afsim_control_proto_goTypes = []any{
	(*ControlCommand)(nil),   // 0: afsim.control.ControlCommand
	(*PauseCommand)(nil),     // 1: afsim.control.PauseCommand
	(*ResumeCommand)(nil),    // 2: afsim.control.ResumeCommand
	(*StepCommand)(nil),      // 3: afsim.control.StepCommand
	(*SetClockRate)(nil),     // 4: afsim.control.SetClockRate
	(*TerminateCommand)(nil), // 5: afsim.control.TerminateCommand
	(*ControlResponse)(nil),  // 6: afsim.control.ControlResponse
}
var file_afsim_control_proto_depIdxs = []int32{
	1, // 0: afsim.control.ControlCommand.pause:type_name -> afsim.control.PauseCommand
	2, // 1: afsim.control.ControlCommand.resume:type_name -> afsim.control.ResumeCommand
	3, // 2: afsim.control.ControlCommand.step:type_name -> afsim.control.StepCommand
	4, // 3: afsim.control.ControlCommand.set_clock_rate:type_name -> afsim.control.SetClockRate
	5, // 4: afsim.control.ControlCommand.terminate:type_name -> afsim.control.TerminateCommand
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_afsim_control_proto_init() }
func file_afsim_control_proto_init() {
	if File_afsim_control_proto != nil {
		return
	}
	file_afsim_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlCommand_Pause)(nil),
		(*ControlCommand_Resume)(nil),
		(*ControlCommand_Step)(nil),
		(*ControlCommand_SetClockRate)(nil),
		(*ControlCommand_Terminate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_afsim_control_proto_rawDesc), len(file_afsim_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_afsim_control_proto_goTypes,
		DependencyIndexes: file_afsim_control_proto_depIdxs,
		MessageInfos:      file_afsim_control_proto_msgTypes,
	}.Build()
	File_afsim_control_proto = out.File
	file_afsim_control_proto_goTypes = nil
	file_afsim_control_proto_depIdxs = nil
}
