#!/usr/bin/env bash
# One-time root setup for running the P2-H verification natively inside WSL2 Ubuntu.
# Installs docker.io + Go 1.23, configures a China Docker Hub mirror (Docker Hub is
# blocked from this WSL2 network), adds the invoking user to the docker group, and
# starts dockerd (left running so the host-side agent can drive verify-p2h.sh).
#
# Run ONCE from your Ubuntu shell:
#   sudo bash /mnt/e/AFsim/afsimweb-master/data-platform/scripts/setup-wsl-docker.sh
#
# Idempotent-ish: safe to re-run.
set -e

GO_VERSION="1.23.4"
TARGET_USER="${SUDO_USER:-$(whoami)}"
MIRROR="https://docker.m.daocloud.io"

echo "==> [1/5] apt update + install docker.io, curl, ca-certificates"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y docker.io curl ca-certificates

echo "==> [2/5] install Go ${GO_VERSION} to /usr/local/go (if missing/old)"
NEED_GO=1
if [ -x /usr/local/go/bin/go ]; then
  cur=$(/usr/local/go/bin/go version | awk '{print $3}')
  if [ "$cur" = "go${GO_VERSION}" ]; then NEED_GO=0; echo "    already ${cur}"; fi
fi
if [ "$NEED_GO" = "1" ]; then
  tmp=/tmp/go${GO_VERSION}.linux-amd64.tar.gz
  curl -fL --retry 3 -o "$tmp" "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz"
  rm -rf /usr/local/go
  tar -C /usr/local -xzf "$tmp"
  rm -f "$tmp"
  echo "    installed $(/usr/local/go/bin/go version)"
fi

echo "==> [3/5] configure Docker Hub registry mirror (${MIRROR})"
mkdir -p /etc/docker
cat > /etc/docker/daemon.json <<EOF
{
  "registry-mirrors": ["${MIRROR}"]
}
EOF

echo "==> [4/6] add user '${TARGET_USER}' to docker group"
groupadd -f docker
usermod -aG docker "${TARGET_USER}"

echo "==> [5/6] switch iptables to legacy backend + load netfilter nat modules (WSL2 kernel)"
if [ -x /usr/sbin/iptables-legacy ]; then
  update-alternatives --set iptables /usr/sbin/iptables-legacy || true
fi
if [ -x /usr/sbin/ip6tables-legacy ]; then
  update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || true
fi
echo "    iptables -> $(readlink -f $(command -v iptables) 2>/dev/null || echo unknown)"
# The WSL2 kernel ships the modules but does not auto-load them; load now + on boot.
# Needed: ipv4 nat/filter, addrtype, the bridge driver (docker0), and ipv6 nat/filter.
MODS="ip_tables iptable_nat iptable_filter iptable_raw iptable_mangle xt_addrtype xt_conntrack xt_MASQUERADE xt_mark xt_comment xt_tcpudp xt_multiport xt_nat nf_nat nf_conntrack ipt_REJECT nf_reject_ipv4 bridge br_netfilter veth overlay ip6_tables ip6table_nat ip6table_filter ip6table_raw ip6table_mangle"
for m in $MODS; do
  modprobe "$m" 2>/dev/null && echo "    modprobe $m ok" || echo "    modprobe $m skipped"
done
printf '%s\n' $MODS > /etc/modules-load.d/docker-wsl.conf

echo "==> [6/6] (re)start dockerd"
systemctl reset-failed docker.service 2>/dev/null || true
service docker restart || service docker start
sleep 4

echo "==> [boot] install systemd drop-in: load modules before dockerd + retry until ready"
# WSL ignores [boot].command when systemd=true, and systemd-modules-load is unreliable
# here. docker.service ExecStartPre loads modules; module loading can fail very early in
# WSL boot, so we also disable the start rate-limit and retry so docker comes up once the
# system is ready. The script logs each modprobe result to the journal (tag wsl-modules).
cat > /usr/local/sbin/docker-wsl-modules.sh <<EOF
#!/bin/sh
# Auto-generated by setup-wsl-docker.sh: load netfilter modules Docker needs on WSL2.
for m in ${MODS}; do
  if modprobe "\$m" 2>&1; then echo "wsl-modules: ok \$m"; else echo "wsl-modules: FAIL \$m rc=\$?"; fi
done
exit 0
EOF
chmod +x /usr/local/sbin/docker-wsl-modules.sh
mkdir -p /etc/systemd/system/docker.service.d
cat > /etc/systemd/system/docker.service.d/wsl-modules.conf <<EOF
[Unit]
StartLimitIntervalSec=0
[Service]
ExecStartPre=/usr/local/sbin/docker-wsl-modules.sh
Restart=on-failure
RestartSec=3
EOF
# Drop the ineffective [boot] command a previous run may have added (ignored under systemd).
sed -i '\#command = /usr/local/sbin/docker-wsl-boot.sh#d' /etc/wsl.conf 2>/dev/null || true
rm -f /usr/local/sbin/docker-wsl-boot.sh
systemctl daemon-reload
systemctl restart docker
sleep 3
echo "    docker.service ExecStartPre + retry installed"

echo "==> verify dockerd is up"
docker version --format 'server={{.Server.Version}}' || { echo "dockerd not responding"; exit 1; }

echo ""
echo "SETUP DONE."
echo "  - docker:  $(docker --version)"
echo "  - go:      $(/usr/local/go/bin/go version)"
echo "  - mirror:  ${MIRROR}"
echo "  - user '${TARGET_USER}' added to docker group (new shells get it automatically)"
echo ""
echo "dockerd is left RUNNING. You can now tell the agent to run the P2-H verification."
